openapi: 3.0.0
info:
  title: API Segurança
  version: 0.1
tags:
  - name: usuarios
paths:
  /usuarios:
    post:
      tags:
        - usuarios
      requestBody:
        content:
          application/json:
            type: object
            properties:
                email: 
                  type: string
                senha:
                  type: string
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
  /usuarios/login:
    post:
      tags:
        - usuarios
      requestBody:
        content:
          application/json:
            type: object
            properties:
                email: 
                  type: string
                senha:
                  type: string
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        401:
          content: 
            application/json:
              schema:
                $ref: '#/componenst/schemas/Mensagem'
  /usuarios/renovar:
components:
  schemas:
    Usuario:
      type: object
      properties:
        email:
          type: string
        senha:
          type: string
        saldo:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
  securitySchemes:
